### GET HEALTH CHECK
GET {{ url }}/health

### GET BANK DATA
GET {{ url }}/basic/get-all

### SEARCH BANK DATA
GET {{ url }}/basic/search?query=return
    
### SEARCH BANK DATA WITH AGENTS
GET {{ url }}/advanced/search?query=return